# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Web_React_Native_Webpack_Babel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Firebase/Core'
  # Pods for Web_React_Native_Webpack_Babel

  target 'Web_React_Native_Webpack_Babel-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'


    pod 'react-native-maps', :path => '../node_modules/react-native-maps'

    pod 'RNSVG', :path => '../node_modules/react-native-svg'

  end

  target 'Web_React_Native_Webpack_BabelTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
